apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: logrus-with-otlp
  name: logrus-with-otlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logrus-with-otlp
  strategy: {}
  template:
    metadata:
      labels:
        app: logrus-with-otlp
    spec:
      containers:
      - command:
        - /usr/local/bin/logrus-with-otlp
        - "-otlp-insecure"
        - "-otlp-endpoint"
        - "otel-collector.openshift-logging.svc.cluster.local:4317"
        image: quay.io/akaris/logrus-with-otlp:latest
        name: logrus-with-otlp